### ISSUE TITLE
Falta solución del ejercicio número 13

### ISSUE THREAD

**Issue by rcedazo** [informatica-ieef-etsidi/vectores-e105-ee105#1]
Por si no ha quedado claro, el programa tiene que calcular el máximo y el mínimo de todos los elementos de una matriz. Ejemplo, para la matriz:

[[1, 3, 4], 
[5, -1, 2]]

Tiene que devolver máximo 5 y mínimo -1.

**Comment by raquelinformatica** [comment]
He subido el ejercicio resuelto sólo para calcular el mínimo. Faltaría calcular el máximo.
